language: node_js
node_js:
  - node

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm ci

before_script:
  - npm run lint
  - npm run test

script:
  - npm run build

after_success:
  - npx codecov

notifications:
  email:
    on_failure: change
    on_success: change
